### PR TITLE
Fixed name of adJ_pricing_table resolves #4

### LINKED ISSUE #4: Fix adJ_pricing_table name
Inadvertent capital J in the object name.

### PR DESCRIPTION
**Pull request by orderlyquant**

### CODE REVIEW

File: get_security_price_data.R [hunk 1]
```diff
@@ -82,7 +82,7 @@ adJ_pricing_table <- pricing_table %>%
   ) %>% 
   ungroup()
 
-write_csv(adJ_pricing_table, fs::path(base_dir, "data", "adj_pricing_table.csv"))
+write_csv(adj_pricing_table, fs::path(base_dir, "data", "adj_pricing_table.csv"))
```
Comment (hdshea) [inline get_security_price_data.R:85]: Got it.  Thanks.
